### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bugerry87** [restorecommerce/access-control-srv#6]
# Environment

access-control-srv

- Ubuntu 20.04 LTS
- NPM 7.7.6
- NodeJS v14.16.0

# What was done

- Backing System is running (only!)
- Packages installed `npm install`
- Executed build `npm run build`
- Executed pretest `npm run pretest` (FAILES!!!)

# Error Snippits

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'winston-elasticsearch'
Require stack:
- /home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/node_modules/@restorecommerce/logger/dist/elasticsearch.js
- /home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/node_modules/@restorecommerce/logger/dist/index.js
- /home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/lib/events/index.js
- /home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/lib/index.js
- /home/gerald/nfuse/restorecommerce/access-control-srv/setupTopics.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/node_modules/@restorecommerce/logger/dist/elasticsearch.js:4:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/node_modules/@restorecommerce/logger/dist/elasticsearch.js',
    '/home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/node_modules/@restorecommerce/logger/dist/index.js',
    '/home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/lib/events/index.js',
    '/home/gerald/nfuse/restorecommerce/access-control-srv/node_modules/@restorecommerce/kafka-client/lib/index.js',
    '/home/gerald/nfuse/restorecommerce/access-control-srv/setupTopics.js'
  ]
}
```

**Comment by Arun-KumarH** [comment]
Pretest seems to run fine and tests as well:
https://github.com/restorecommerce/access-control-srv/runs/2235177236

**Comment by vanthome** [comment]
@bugerry87 can we close this?
